insert into comment values
(1, 1, 'Go, Go, Go!', 1, 'You Rock!'),
(2, 2, 'We will help!', 2, 'Yeah!'),
(3, 2, 'Go, Go, Go!', 3, 'Come on!'),
(4, 1, 'So nice', 4, 'We love it'),
(5, 3, 'Could you upload your pictures somewhere?', 5, 'We want to see it!'),
(6, 4, 'When can I expect to go to your palace?', 6, 'Palace invitation'),
(7, 1, 'Dolor sit', 1, 'Lorem Ipsum'),
(8, 2, 'Dolor sit', 2, 'Lorem Ipsum'),
(9, 2, 'Dolor sit', 3, 'Lorem Ipsum'),
(10, 3, 'Dolor sit', 4, 'Lorem Ipsum'),
(12, 4, 'Dolor sit', 5, 'Lorem Ipsum'),
(13, 3, 'Dolor sit', 6, 'Lorem Ipsum'),
(14, 1, 'Dolor sit', 1, 'Lorem Ipsum'),
(15, 2, 'Dolor sit', 2, 'Lorem Ipsum'),
(16, 4, 'Dolor sit', 3, 'Lorem Ipsum'),
(17, 4, 'Dolor sit', 4, 'Lorem Ipsum'),
(18, 4, 'Dolor sit', 5, 'Lorem Ipsum'),
(19, 4, 'Dolor sit', 6, 'Lorem Ipsum');
